---
title: "Knitr Project"
author: "Jackson Pham"
date: "`r Sys.Date()`"
output: html_document
---

# Part 1: Loading and Reprocessing Data

```{r, echo = TRUE}

data <- read.csv("Downloads/activity.csv")
head(data)
summary(data)

# Determine the data frame and value, ignore all zero value
# And NA value

```

# Part 2: What is mean total number of steps taken per day?

```{r, echo = TRUE}

total_steps_per_day <- aggregate(steps ~ date, data = data, FUN = sum)

# Determine the total amount of steps per day

hist(total_steps_per_day$steps, main = "Total Steps Count Per Day", xlab = "Total Steps", ylab = "Frequency", col = "lightblue")

# Graph the histogram of date vs total steps count, the date is counted as
# Frequency from 1 to 53 where 1 is the starting date of 2012-10-02 and 53 
# Represent 2012-11-29

```

# Part 3: What is the average daily activity pattern?

```{r, echo = TRUE}

avg_steps_per_interval <- aggregate(steps ~ interval, data = data, FUN = mean)

# Determine the average steps per interval using the function aggregate with means
# This allow use to make the time series graph

plot(avg_steps_per_interval$interval, avg_steps_per_interval$steps, type = "l", xlab = "5-Minute Interval", ylab = "Average Number of Steps", main = "Average Number of Steps Taken per 5-Minute Interval")

# Plot the time series graph

max_interval <- avg_steps_per_interval$interval[which.max(avg_steps_per_interval$steps)]

# Find the interval with the maximum average number of steps

max_interval

```

# Part 4: Imputing missing values

```{r, echo = TRUE}

total_missing_value <- sum(is.na(data$steps))
total_missing_value

# Determine total missing values

# Create a copy of the original dataset

new_data <- total_steps_per_day

# Iterate over each row in the data frame

for (i in 1:nrow(new_data)) {
  # Check if the steps value is missing or zero
  if (is.na(new_data$steps[i]) | new_data$steps[i] == 0) {
    # Find the mean of steps for the corresponding date
    mean_steps <- mean(new_data$steps[new_data$date == new_data$date[i]], na.rm = TRUE)
    # Replace the missing or zero value with the mean
    new_data$steps[i] <- mean_steps
  }
}

# Present first few lines of the new data

head(new_data)

# Create a histogram of the total number of steps taken each day

hist(new_data$steps, main = "Total Steps Taken Each Day", xlab = "Total Steps", ylab = "Frequency", col = "lightblue")

# Calculate the mean and median total number of steps taken per day

mean_steps_per_day <- mean(new_data$steps, na.rm = TRUE)
median_steps_per_day <- median(new_data$steps, na.rm = TRUE)

mean_steps_per_day
median_steps_per_day

```

# Part 5: Are there differences in activity patterns between weekdays and weekends?

```{r, echo = TRUE}

# Copy of new_data to a separate variable

new_data_weekday <- new_data
new_data_weekday$date <- as.Date(new_data$date)

# Create a for loop that goes through every column in the dataframe 
# new_data$date using the weekdays() function to create a new coulmnn
# with the weekday inserted

new_data_weekday$day_type <- factor(weekdays(new_data_weekday$date) %in% c("Saturday", "Sunday"),
                        levels = c(FALSE, TRUE),
                        labels = c("weekday", "weekend"))

# Print out first few row of the result

head(new_data_weekday)

# Load ggplot2

library(ggplot2)

# Turn weekday into 0, and weekend into 1 as a binary number

new_data_weekday$day_type_binary <- ifelse(new_data_weekday$day_type == "weekday", 0, 1)

head(new_data_weekday)

# Find the average number of steps between weekday and weekend

mean_steps <- aggregate(steps ~ day_type_binary, data = new_data_weekday, FUN = mean)

# Graph the bar graph between mean steps of weekday and weekend

ggplot(mean_steps, aes(x = factor(day_type_binary), y = steps, fill = factor(day_type_binary))) +
  geom_bar(stat = "identity") +
  labs(title = "Mean Number of Steps by Day Type",
       x = "Day Type",
       y = "Mean Number of Steps") +
  scale_x_discrete(labels = c("Weekday", "Weekend")) +
  theme_minimal()

# The graph shows that more steps are taken in weekend than weekday

```






